# Project
TYPE_NOTIFICATION_ACTION_PROJECT = 'action_project'
TYPE_NOTIFICATION_ADD_INTO_PROJECT = 'add_into_project'
TYPE_NOTIFICATION_DELETE_PROJECT = 'delete_project'
TYPE_NOTIFICATION_EDIT_PROJECT = 'edit_project'
# Message
TYPE_NOTIFICATION_ACTION_MESSAGE = 'action_message'
TYPE_NOTIFICATION_NEW_MESSAGE = 'new_message'
# User
TYPE_NOTIFICATION_ACTION_USER = 'action_user'
TYPE_NOTIFICATION_ADMIN_USER = 'admin_user'
TYPE_NOTIFICATION_ARCHIVE_USER = 'archive_user'
